/*   This is the base file for the Sokoban assignment - include this one in your HTML page, before you add the main script file*/

/*   Enum of CSS Classes for the static elements   */
var Tiles = {
    Wall: "tile-wall",
    Space: "tile-space",
    Goal: "tile-goal",
  };
  
  /*   Enum of CSS Classes for the moving elements   */
  var Entities = {
    Character: "entity-player",
    Block: "entity-block",
    BlockDone: "entity-block-goal",
  };
  



  var KeystrokeEventArea;
  



  console.log("is responding");
  /*  Legend
      W = Wall
      B = Movable block
      P = Player starting position
      G = Goal area for the blocks
  */
  var tileMap01 = {
    width: 19,
    height: 16,
    mapGrid: [
      [
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
      ],
      [
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
      ],
      [
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
      ],
      [
        [" "],
        [" "],
        [" "],
        [" "],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
      ],
      [
        [" "],
        [" "],
        [" "],
        [" "],
        ["W"],
        [" "],
        [" "],
        [" "],
        ["W"],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
      ],
      [
        [" "],
        [" "],
        [" "],
        [" "],
        ["W"],
        ["B"],
        [" "],
        [" "],
        ["W"],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
      ],
      [
        [" "],
        [" "],
        ["W"],
        ["W"],
        ["W"],
        [" "],
        [" "],
        ["B"],
        ["W"],
        ["W"],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
      ],
      [
        [" "],
        [" "],
        ["W"],
        [" "],
        [" "],
        ["B"],
        [" "],
        ["B"],
        [" "],
        ["W"],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
      ],
      [
        ["W"],
        ["W"],
        ["W"],
        [" "],
        ["W"],
        [" "],
        ["W"],
        ["W"],
        [" "],
        ["W"],
        [" "],
        [" "],
        [" "],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
      ],
      [
        ["W"],
        [" "],
        [" "],
        [" "],
        ["W"],
        [" "],
        ["W"],
        ["W"],
        [" "],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
        [" "],
        [" "],
        ["G"],
        ["G"],
        ["W"],
      ],
      [
        ["W"],
        [" "],
        ["B"],
        [" "],
        [" "],
        ["B"],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        ["G"],
        ["G"],
        ["W"],
      ],
      [
        ["W"],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
        [" "],
        ["W"],
        ["W"],
        ["W"],
        [" "],
        ["W"],
        ["P"],
        ["W"],
        ["W"],
        [" "],
        [" "],
        ["G"],
        ["G"],
        ["W"],
      ],
      [
        [" "],
        [" "],
        [" "],
        [" "],
        ["W"],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
      ],
      [
        [" "],
        [" "],
        [" "],
        [" "],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
        ["W"],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
      ],
      [
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
      ],
      [
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
        [" "],
      ],
    ],
  };


  // var createGridItem = document.createElement('div');
  // // gör om arrays till divvar
  // function CreateGrids() {
    
  //   tileMap01.mapGrid.forEach(element => {
  //     // createGridItem += element;
  //     // createGridItem
  //     createGridItem.setAttribute('id', ('x' + ':' + element));
  //     // createGridItem.id += 1;
  //     // createGridItem.className += element+1;

  //     console.log(createGridItem);    
  //     return document.body.appendChild(createGridItem);
  //   });
  // }

  var createGridItem = document.createElement('div');
  for (g in tileMap01.mapGrid) {
    
    // createGridItem;
    createGridItem.id = 'y:'+g;
    console.log(g);
  }
  document.body.appendChild(createGridItem);
  
  // CreateGrids();


  //konstruera playArea som capturar alla keystrokes

